### ISSUE TITLE
TypeError: must be str, not ValueError

### ISSUE THREAD

**Issue by mauriciochamas** [scikit-learn-contrib/boruta_py#40]
Sorry I can't reproduce your code with my dataset. Here's the error text:
rf = RandomForestClassifier(n_jobs = -1, class_weight = 'balanced', max_depth = 5)
feat_selector = BorutaPy(rf, n_estimators = 'auto', verbose = 2, random_state = 1)
feat_selector.fit(x, y)

Traceback (most recent call last):

  File "<ipython-input-107-c040bd29222e>", line 1, in <module>
    feat_selector.fit(x, y)

  File "C:\Users\Usuario\AnacondaProjects\scikit-learn-contrib-boruta_py-c370f01\boruta\boruta_py.py", line 201, in fit
    return self._fit(X, y)

  File "C:\Users\Usuario\AnacondaProjects\scikit-learn-contrib-boruta_py-c370f01\boruta\boruta_py.py", line 285, in _fit
    cur_imp = self._add_shadows_get_imps(X, y, dec_reg)

  File "C:\Users\Usuario\AnacondaProjects\scikit-learn-contrib-boruta_py-c370f01\boruta\boruta_py.py", line 408, in _add_shadows_get_imps
    imp = self._get_imp(np.hstack((x_cur, x_sha)), y)

  File "C:\Users\Usuario\AnacondaProjects\scikit-learn-contrib-boruta_py-c370f01\boruta\boruta_py.py", line 383, in _get_imp
    'estimator cannot be fitted to your data.\n' + e)

TypeError: must be str, not ValueError

**Comment by Taakn** [comment]
@mauriciochamas I'm getting the same error. did you manager to fix it? Thanks!

**Comment by mauriciochamas** [comment]
sys.path.append(r'C:\Users\Usuario\AnacondaProjects\scikit-learn-contrib-boruta_py-c370f01')
from boruta import BorutaPy
base = df.values
x = base[:, 1:]
y = base[:, 0]

**Comment by zhengzhuang3** [comment]
I am also getting the same error. Could you please explain how it happens and how to fix this issue? Thanks!

**Comment by AdityaSoni19031997** [comment]
The solution is written above

**Comment by zhengzhuang3** [comment]
Thank you. My error has changed as follows. I wonder whether Boruta can handle regression cases where y is a continuous 1-D array

> ValueError: Please check your X and y variable. The providedestimator cannot be fitted to your data.
> Unknown label type: 'continuous'

**Comment by AdityaSoni19031997** [comment]
It can handle provided you are doing exactly what needs to be done...
